optional trailing port arguments ip4/ip6
troglobit/mcjoin pull request #25
Opened 2022-03-04 14:04 UTC by adamyg

ticket #18

2022-03-05 10:03 UTC, troglobit commented
Hi and thank you for your contribution!  I've been auditing your changes to fix #18, and if I focus on the functional changes only, it solves the problem :smiley: 

However, there are lots of unrelated changes to the tree, e.g. good whitespace fixes and some unmotivated ones.  Each of these should either be a separate commit, or dropped from this patch series altogether.  Also, when submitting changes to an upstream project you should try to clean up the commits so they are clear and isolated, here you remove code from the first commit in the second due to copy-paste I guess.  You also need to write a summary of your changes with motivations.

Now, I can do a GitHub review of each of your changes and you can take this opportunity to learn a thing or two, but that'll take me a while to finish, so before I spend some of my weekend on it, I have to ask; are you interested in that type of feedback and willing to do the cleanup necessary?

2022-03-07 03:26 UTC, adamyg commented
Hi, sure - we all work to a different set of rules, happy to experience alternatives. Shall admit commit a little messy, pushed from an internal repo and then realized it was an older branch which in-turn i then updated; possible rebase use-case; yet we never look at individual commits only the resulting artifact. As for white-space tweaks, no issues, stopped having these type of wars years ago; can refactor and/or clang-format.

2022-03-07 05:14 UTC, troglobit commented
OK great, I'll send you a detailed review later today!

2022-03-07 07:01 UTC, troglobit requested changes
There, lots of minor details and a few major ones (`getuid()` in particular).

I think the easiest way to fix the mess with the two commits is to just to squash them when rebasing on the latest master.  But I leave that up to you to sort out, now that you're aware of it.

2022-03-07 15:00 UTC, adamyg commented
pr comments applied

2022-03-07 20:16 UTC, troglobit commented
Awesome, looks *much* better, thank you!  There are a few lingering things though that I'd like you to address before I merge, I've left those comments open from the first review, and updated a couple of them.

2022-03-08 01:47 UTC, adamyg commented on src/inetaddr.c
> +	if (port < 1024 && geteuid()) {
original specialized geteuid() check restored: see main

2022-03-08 01:52 UTC, adamyg commented on src/mcjoin.c
original source restored

2022-03-08 07:43 UTC, troglobit commented
Great work on this, thank you for taking the time! :heart:

2022-03-08 07:43 UTC, troglobit approved these changes

2022-03-08 07:48 UTC, merged